### ISSUE TITLE
ShellCheck Thread

### ISSUE THREAD

**Issue by brandleesee** [B00merang-Project/Shell-Scripts#1]
@Elbullazul 

Posted [install.sh raw](https://raw.githubusercontent.com/B00merang-Project/TransPack/master/install.sh) in [shellcheck](http://www.shellcheck.net/) and received the below listed *perceived* errors. The lines to which these errors belong to are listed at the end of this post.

### Summary of *errors*

| These | are | all | errors! |
| :-----: | :-----: | :-----: | :-----: |
| [SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164) | ~~[SC2129](https://github.com/koalaman/shellcheck/wiki/SC2129)~~ | [SC2035](https://github.com/koalaman/shellcheck/wiki/SC2035) | [SC2004](https://github.com/koalaman/shellcheck/wiki/SC2004) |
| [SC2024](https://github.com/koalaman/shellcheck/wiki/SC2024) | [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) | [SC2167](https://github.com/koalaman/shellcheck/wiki/SC2167) | ~~[SC2068](https://github.com/koalaman/shellcheck/wiki/SC2068)~~ |
| [SC2165](https://github.com/koalaman/shellcheck/wiki/SC2165) | ~~[SC2053](https://github.com/koalaman/shellcheck/wiki/SC2053)~~ | ~~[SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086)~~ | [SC2162](https://github.com/koalaman/shellcheck/wiki/SC2162) |
| [SC2059](https://github.com/koalaman/shellcheck/wiki/SC2059) | ~~[SC2006](https://github.com/koalaman/shellcheck/wiki/SC2006)~~ | [SC2181](https://github.com/koalaman/shellcheck/wiki/SC2181) | [SC2046](https://github.com/koalaman/shellcheck/wiki/SC2046) |

This will be a very long task to accomplish - *not complaining* - so it will take time. As always I will be posting results and improvements in this issue thread and pull requests with thorough explanations. Once this is finished - *lord know when!* - I'll tackle the uninstall raw.

### Errors report from website 

```
Line 59:
  cd tmp
  ^-- SC2164: Use cd ... || exit in case cd fails.
```
 
~~Line 108:~~
  ~~echo "$zipgtk" >>"$LOG"~~
  ~~^-- SC2129: Consider using { cmd1; cmd2; } >> file instead of individual redirects.~~

```
Line 122:
  cd "$TMP"
  ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 151:
  cd "$TMP"
  ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 161:
  cd GTK
  ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 166:
    rm -rf */"${files[$runs]}"    # remove directories in active array item in all sub-folders
           ^-- SC2035: Use ./*glob* or -- *glob* so names with dashes won't become options.
 
Line 167:
    runs=$(($runs+1))             # update actual runtimes
            ^-- SC2004: $/${} is unnecessary on arithmetic variables.
 
Line 171:
  cd "$TMP"
  ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 179:
  cd "$TMP/GTK" # enter GTK themes folder
  ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 209:
  cd "$TMP/GTK"
  ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 353:
      sudo "$pkgman" install gnome-shell-extension-user-theme >>"$LOG"
                                                              ^-- SC2024: sudo doesn't affect redirects. Use .. | sudo tee -a file
            ^-- SC2154: pkgman is referenced but not assigned.
```

~~Line 453:~~
  ~~for f in ${!flags[@]}~~
  ~~^-- SC2167: This parent loop has its index variable overridden.~~
           ~~^-- SC2068: Double quote array expansions to avoid re-splitting elements.~~
 
~~Line 484:~~
      ~~for f in ${!deskenv[@]} # for every item in the array~~
               ~~^-- SC2068: Double quote array expansions to avoid re-splitting elements.~~
      ~~^-- SC2165: This nested loop overrides the index variable of its parent.~~

~~Line 486:~~
        ~~if [[ $override == $f ]];then # assign WM value if DE matches parameter~~
                           ~~^-- SC2053: Quote the rhs of == in [[ ]] to prevent glob matching.~~

~~Line 576:~~
  ~~if [ $DE == 'gnome' ]; then # Metro application only available for GNOME~~
       ~~^-- SC2086: Double quote to prevent globbing and word splitting.~~

```
Line 577:
    read -n 1 -p "Windows 10 Light = 1   Windows 10 Dark = 2   Metro Dark = 3 [1]:" choice
    ^-- SC2162: read without -r will mangle backslashes.
 
Line 580:
    read -n 1 -p "Windows 10 Light = 1   Windows 10 Dark = 2 [1]:" choice
    ^-- SC2162: read without -r will mangle backslashes.
 
Line 586:
    printf "\nPlease chose a number between 1 and $max!\n"
           ^-- SC2059: Don't use variables in the printf format string. Use printf "..%s.." "$foo".
```

~~Line 610:~~
    ~~get_flags $@ # send all flags to detect flags function~~
              ~~^-- SC2068: Double quote array expansions to avoid re-splitting elements.~~

```
Line 617:
  read -n 1 -s -p "Press any key to continue"
  ^-- SC2162: read without -r will mangle backslashes.
 ```

~~Line 624:~~
  ~~today=`date +%Y-%m-%d_%k:%M:%S`~~
        ~~^-- SC2006: Use $(..) instead of legacy `..`.~~

~~Line 631:~~
  ~~if [ $bash_v -lt 4 ]; then~~
       ~~^-- SC2086: Double quote to prevent globbing and word splitting.~~

```
Line 644:
  if [ $? -eq 0 ]; then
       ^-- SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.
 
Line 652:
  WM="$(xprop -id $(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}') -notype -f _NET_WM_NAME 8t | grep _NET_WM_NAME)"
                  ^-- SC2046: Quote this to prevent word splitting.
 
Line 710:
    cd GTK/Windows\ 10\ Light
    ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 723:
    cd GTK/Windows\ 10\ Light
    ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 728:
  cd "$TMP"
  ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 770:
        cd GTK/Windows\ 10\ Light/tint2
        ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 775:
      cd "$TMP/GTK/Windows 10 Light"
      ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 777:
      cd ../Windows\ 10\ Dark
      ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 790:
        cd GTK/Windows\ 10\ Light/fluxbox
        ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 793:
        cd ../../Windows\ 10\ Dark/fluxbox
        ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 797:
        cd "$TMP/GTK"
        ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 798:
        rm -rf */fluxbox
               ^-- SC2035: Use ./*glob* or -- *glob* so names with dashes won't become options.
 
Line 803:
        cd GTK/Windows\ 10\ Light/fluxbox
        ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 806:
        cd ../../Windows\ 10\ Dark/fluxbox
        ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 810:
        cd "$TMP/GTK"
        ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 811:
        rm -rf */fluxbox
               ^-- SC2035: Use ./*glob* or -- *glob* so names with dashes won't become options.
 
Line 816:
      cd "$TMP"
      ^-- SC2164: Use cd ... || exit in case cd fails.
 
Line 862:
  cd "$TMP/.."
  ^-- SC2164: Use cd ... || exit in case cd fails.
```

**Comment by Elbullazul** [comment]
argh! shell syntax xD

thanks for your help

**Comment by brandleesee** [comment]
Closing as there seems to be a revamp coming. Also it is two years old.
